backend:
  name: github
  repo: dzikrifauzan-app/Sleep-science-hub
  branch: gh-pages

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://dzikrifauzan-app.github.io/Sleep-science-hub

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
